version: '3.7'

services:
  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      # - --entrypoints.adminer.address=:9090
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      - --api.dashboard=true
      - --certificatesresolvers.cloudflare.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesresolvers.http.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesresolvers.http.acme.storage=acme.json
      - --certificatesresolvers.http.acme.httpchallenge.entrypoint=http
      - --log.level=ERROR
      # TLS 1.2+
      - --providers.file.filename=/traefik_conf.yml
      ## Letsencrypt staging server ##
      # - --certificatesresolvers.cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      # - --certificatesresolvers.http.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
    environment:
      FQDN: "${FQDN}"
      CLOUDFLARE_EMAIL: "${CLOUDFLARE_EMAIL}"
      CLOUDFLARE_API_KEY: "${CLOUDFLARE_API_KEY}"
      MG_API_KEY: "${MG_API_KEY}"
      DEV_SMTP_LOGIN: "${DEV_SMTP_LOGIN:-}"
      DEV_SMTP_PASS: "${DEV_SMTP_PASS:-}"
      DEV_SMTP_FROM: "${DEV_SMTP_FROM:-}"
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/storage/rhdwp/letsencrypt/acme.json:/acme.json
      - ./conf.yml:/traefik_conf.yml
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.entrypoints=http"
        - "traefik.http.routers.api.rule=Host(`${FQDN}`)"
        - "traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.api-https.entrypoints=https"
        - "traefik.http.routers.api-https.tls=true"
        - "traefik.http.routers.api-https.tls.certresolver=cloudflare"
        - "traefik.http.routers.api-https.tls.domains[0].main=${FQDN}"
        # - "traefik.http.routers.api-https.tls.domains[0].sans=sub1.${FQDN},sub2.${FQDN}"
        - "traefik.http.routers.api-https.middlewares=api-auth"
        - "traefik.http.routers.api-https.rule=Host(`${FQDN}`)"
        - "traefik.http.middlewares.api-auth.basicauth.users=admin:$$2y$$05$$7t25C0myBoWErPjCUsEDPe/TKLjdiywW4HchSJiKNmK5nZk2saVLW"
        - "traefik.http.routers.api.middlewares=api-https-redirect"
        - "traefik.http.routers.api-https.service=api@internal"
        - "traefik.http.services.api-https.loadbalancer.server.port=8080"
        ## Buffering ##
        # - "traefik.https.middlewares.limit.buffering.maxRequestBodyBytes=4000000000"
        # - "traefik.https.middlewares.limit.buffering.memRequestBodyBytes=4000000000"
        # - "traefik.https.middlewares.limit.buffering.maxResponseBodyBytes=4000000000"
        # - "traefik.https.middlewares.limit.buffering.retryExpression=IsNetworkError() && Attempts() < 2"

  ## RHDWP: Adminer ##
  # adminer:
  #   image: adminer
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=mysql
  #     - ADMINER_DESIGN=nicu
  #   networks:
  #     - %%project_label%%_internal
  #   ports:
  #     - 9090:9090
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.adminer.entrypoints=adminer"
  #     - "traefik.http.routers.adminer.rule=Host(`${FQDN}`)"
  ## RHDWP: Adminer end ##

networks:
  proxy:
    driver: overlay
    name: proxy
  ## RHDWP: Adminer ##
  # %%project_label%%_internal:
  #   driver: overlay
  #   name: %%project_label%%_internal
  ## RHDWP: Adminer end ##