version: '3'

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: unless-stopped
    command:
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      ## RHDWP: API ##
      # - --api.dashboard=true
      ## RHDWP: API end ##
      ## RHDWP: LetsEncrypt Staging ##
      # - --certificatesresolvers.cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      ## RHDWP: LetsEncrypt Staging end ##
      - --certificatesresolvers.cloudflare.acme.email=${CF_API_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --log.level=error
      # - --log.filePath=./log/error.log
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    ## RHDWP: useLabels ##
    # labels:
    ## RHDWP: useLabels end ##
    ## RHDWP: Buffering ##
    #   - "traefik.https.middlewares.limit.buffering.maxRequestBodyBytes=4000000000"
    #   - "traefik.https.middlewares.limit.buffering.memRequestBodyBytes=4000000000"
    #   - "traefik.https.middlewares.limit.buffering.maxResponseBodyBytes=4000000000"
    #   - "traefik.https.middlewares.limit.buffering.retryExpression=IsNetworkError() && Attempts() < 2"
    ## RHDWP: Buffering end ##
    ## RHDWP: API ##
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.entrypoints=http"
    #   - "traefik.http.routers.api.rule=Host(`monitor.${FQDN}`)"
    #   - "traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https"
    #   - "traefik.http.routers.api-https.entrypoints=https"
    #   - "traefik.http.routers.api-https.tls=true"
    #   - "traefik.http.routers.api-https.tls.certresolver=cloudflare"
    #   - "traefik.http.routers.api-https.tls.domains[0].main=monitor.${FQDN}"
    #   - "traefik.http.routers.api-https.middlewares=api-auth"
    #   - "traefik.http.routers.api-https.rule=Host(`monitor.${FQDN}`)"
    #   - "traefik.http.middlewares.api-auth.basicauth.users=admin:$$2y$$05$$7t25C0myBoWErPjCUsEDPe/TKLjdiywW4HchSJiKNmK5nZk2saVLW"
    #   - "traefik.http.routers.api.middlewares=api-https-redirect"
    #   - "traefik.http.routers.api-https.service=api@internal"
    ## RHDWP: API end ##
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
  
  ## RHDWP: Adminer ##
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=mysql
  #   networks:
  #     - %%project_label%%_internal
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.adminer.rule=Host(`adminer.${FQDN}`)"
  ## RHDWP: Adminer end ##

networks:
  web:
    external: true
  ## RHDWP: Adminer ##
  # %%project_label%%_internal:
  #   external: true
  ## RHDWP: Adminer end ##
