version: '3'

services:
  traefik:
    image: traefik:v2.1
    container_name: traefik
    restart: unless-stopped
    command:
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      # - --api.dashboard=true
      # - --certificatesresolvers.cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cloudflare.acme.email=${CF_API_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=acme.json
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --log.level=debug
    security_opt:
      - no-new-privileges:true
    networks:
      - web
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.entrypoints=http"
    #   - "traefik.http.routers.api.rule=Host(`monitor.${FQDN}`)"
    #   - "traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https"
    #   - "traefik.http.routers.api-https.entrypoints=https"
    #   - "traefik.http.routers.api-https.tls=true"
    #   - "traefik.http.routers.api-https.tls.certresolver=cloudflare"
    #   - "traefik.http.routers.api-https.tls.domains[0].main=monitor.${FQDN}"
    #   - "traefik.http.routers.api-https.middlewares=api-auth"
    #   - "traefik.http.routers.api-https.rule=Host(`monitor.${FQDN}`)"
    #   - "traefik.http.middlewares.api-auth.basicauth.users=admin:$$2y$$05$$7t25C0myBoWErPjCUsEDPe/TKLjdiywW4HchSJiKNmK5nZk2saVLW"
    #   - "traefik.http.routers.api.middlewares=api-https-redirect"
    #   - "traefik.http.routers.api-https.service=api@internal"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.${FQDN}`)"

networks:
  web:
    external: true
  backend:
    external: true