version: '3.3'

services:
  traefik:
    image: 'traefik:1.7.2-alpine'
    labels:
      - 'traefik.frontend.rule=Host:monitor.traefik.roundhouse-designs.com'
      - 'traefik.port=8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$PWD/traefik.toml:/traefik.toml'
      - '$PWD/acme.json:/acme.json'
    ports:
      - '80:80'
      - '443:443'
    network_mode: web