## Use rhdwp/start.sh to generate docker-compose.yml

version: '3.3'

services:
  traefik:
    image: 'traefik:1.7.2-alpine'
    # labels:
      # - 'traefik.frontend.rule=Host:monitor.$HOSTNAME.roundhouse-designs.com'
      # - 'traefik.dashboard.port=8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik.toml:/traefik.toml'
      - './acme.json:/acme.json'
    ports:
      - '80:80'
      - '443:443'
    network_mode: web
