api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

certificatesResolvers:
  http:
    acme:
      email: admin@roundhouse-designs.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

# log:
#   filePath: "/srv/rhdwp/traefik/traefik.log"
#   level: DEBUG