####
## Use build.sh to generate traefik.toml
####

defaultEntryPoints = ["http", "https"]

[entryPoints]
#  [entryPoints.dashboard]
#    address = ":8080"
#    [entryPoints.dashboard.auth]
#      [entryPoints.dashboard.auth.basic]
#        users = ["admin:$apr1$6EMGK3WJ$1r1kQ91PV5n2aDbFCMJUh0"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
  [entryPoints.livereload]
    address = ":9999"

#[api]
#entrypoint="dashboard"

[acme]
email = "admin@roundhouse-designs.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
# ACME staging
# [certificatesResolvers.letsencrypt.acme]
#   caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[docker]
domain = "%%hostname%%"
watch = true
network = "web"

# [log]
#   level = "DEBUG"
